# .github/workflows/ci.yml
name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # install your app so `import flaskr` works
          pip install -e examples/tutorial

      - name: Run tests with coverage
        run: |
          pytest examples/tutorial/tests \
            --maxfail=1 --disable-warnings \
            --cov=flaskr --cov-report=term-missing --cov-report=html

